### ISSUE TITLE
Can't open same serial port again after closed it.

### ISSUE THREAD

**Issue by willhuo** [crozone/LinuxSerialPort#10] opened 2018-01-15 05:55 UTC
I can not open the same serial port which I had closed it before.
I used the method to close serial port below.

`public bool CloseSerialPort()
        {
            if(_LinuxSerialPort!=null)
            {
                _Timer.Stop();
                _LinuxSerialPort.Close();
                _LinuxSerialPort.Dispose();
                Log.Default.LogPrint("Serial port closed");
                return true;
            }
            else
            {
                return true;
            }
        }`

Then I quit the program.
When I running the program again. 
Opening the same serial port has blocked.

`        public bool OpenSerialPort()
        {
            if (_LinuxSerialPort == null)
                _LinuxSerialPort = new LinuxSerialPort(_Port);
            _LinuxSerialPort.BaudRate = _Rate;
            Log.Default.LogPrint($"Serialport {_Port} is opening...");
            _LinuxSerialPort.Open();  //block at this line.
            if (_LinuxSerialPort.IsOpen)
            {
                Log.Default.LogPrint($"Serialport {_Port} opened success");
                _Timer.Start();
                return true;
            }
            else
            {
                Log.Default.LogDay("Serialport ttyUSB0 opened failed");
                Log.Default.LogPrint("Serialport ttyUSB0 opened failed");
                return false;
            }
        }`

 _LinuxSerialPort.Open();  //block at this line.

I doult the serial port file hand has not closed when i close the serial port.

**Comment by crozone** [comment] 2018-01-16 23:49
I can't seem to reproduce the bug here, but there are two places this could be blocking:

1) On the serial port `File.Open()`. This call shouldn't block, unless there's something seriously wrong with the serial port driver, so it's unlikely the call is blocking here.

2) When calling `stty`.

After some digging, it appears there is a [known issue](http://lkml.iu.edu/hypermail/linux/kernel/1601.3/03109.html) that can cause `stty` to block. By default, `stty` attempts to drain the TX buffer before applying settings. If the buffer contains data but the port is in a state where the buffer cannot be flushed (eg waiting for flow control), `stty` will hang indefinitely.

To get around this, the `[-]drain` argument was added to the coreutils 8.25 `stty` in [2016](http://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=cb7d8b90a213c0186a8c8ba66da959e1f5930e78) and it's available in Debian 9 (Stretch).

However, there are many versions of `stty` without the `[-]drain` option, and there will need to be a way to detect the `stty` version and use `[-]drain` only when available.
A timeout on the execution of the `stty` command will at least allow an exception to be thrown rather than blocking indefinitely.

@willhuo Just to verify the cause, can you please try the following:

1) Open the serial port as normal
2) Close the port as normal
3) Exit the application
3) Try to run the command `stty -F /dev/ttyUSB0 115200`

If `stty` blocks on the command line, we've found the issue.

**Comment by crozone** [comment] 2019-04-05 06:23
This should be fixed by the latest 1.2.0 release. If you set `EnableDrain = false` before opening, the hang probably shouldn't happen anymore.

**Closed as completed** 2019-04-12 14:44 UTC
